# syntax=docker/dockerfile:1
FROM python:3.7-alpine
RUN mkdir /output
WORKDIR /home

COPY filedata.txt .
COPY transaction.py .
COPY requirements.txt .
RUN pip install -r requirements.txt

CMD ["python3", "./transaction.py", "/output"]